---
- name: "100k event rules"
  hosts: all
  sources:
    - name: generic
      ansible.eda.generic:
        create_index: i
        loop_count: 200000
        payload:
          - name: fred
  rules:
    - name: r1
      condition: event.i is defined
      timeout: 6 minutes
      action:
        none:
