- name: Hello Controller
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 100
  rules:
    - name: "Run job template"
      condition: event.i < 101
      action:
        run_job_template:
          name: five
          organization: Default