---
- name: "generate events"
  hosts: localhost
  sources:
    - name: generic
      ansible.eda.generic:
      create_index: i
      loop_count: 10000
      payload:
        - name: fred
  rules:
    - name: r1
      condition: event.i is defined
      action:
        none:

