- name: Hello Controller
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
  rules:
    - name: "Run job template"
      condition: event.i < 11
      action:
        run_job_template:
          name: one
          organization: Default
