- name: An example EDA webhook
  hosts: localhost
  sources:
    - ansible.eda.pg_listener:
        dsn: ""
        channels:
          - my_events
  rules:
    - name: Say Name
      condition: event is defined
      action:
        run_job_template:
          name: one
          organization: Default
