- name: An example EDA webhook
  hosts: localhost
  sources:
    - ansible.eda.pg_listener:
        dsn: "host=18.206.156.131 port=5432 dbname=testeda user=edalisten password=edalisten"
        channels:
          - my_events
  rules:
    - name: Say Name
      condition: event.name == "Sarath"
      action:
        run_job_template:
          name: one
          organization: Default
