- name: An example EDA webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.message == "Hello from webhook"
      action:
        run_job_template:
          name: eda-demo
          organization: Default

